---
filebeat.inputs:
  - type: log
    paths:
      - /var/log/app/logs/*.log

output.logstash:
  hosts: ["logstash:5044"]

monitoring:
  enabled: true
  elasticsearch:
    hosts: [ "http://elasticsearch:9200" ]
    username: elastic
    password: changeme
