version: "3.7"
services:
  elasticsearch:
    build:
      context: elasticsearch
    restart: "on-failure:20"
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "http://localhost:9200" ]
      interval: 20s
      timeout: 10s
      retries: 10
    environment:
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
